name: repro
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetSource: "https://api.nuget.org/v3/index.json"

defaults:
  run:
    shell: pwsh

jobs:
  pack_net6:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-rc.1.21458.32'
      
    - run: dotnet pack --configuration Release '/p:TargetFramework=net6.0' /bl
      name: Build

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        if-no-files-found: error
        retention-days: 3
        path: "**/*.{binlog,nupkg}"

  pack_net5:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-rc.1.21458.32'
      
    - run: dotnet pack --configuration Release '/p:TargetFramework=net5.0' /bl
      name: Build

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        if-no-files-found: error
        retention-days: 3
        path: "**/*.{binlog,nupkg}"
